services:
  localstack:
    image: localstack/localstack:latest
    container_name: assyncronous-localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: sns,sqs
      DEBUG: "1"
      AWS_DEFAULT_REGION: us-east-1
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  localstack-data:

